# -*- coding: utf-8 -*-
"""DT project-final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tfCLOl_15xaWxJ6D6qfc3-5pRNwckf-h
"""

# ============================================================
#  Macro-Cloud: AI-Driven Personalized Meal Recommendation
#  Run this entire file in Google Colab (cell by cell or all at once)
#  BEFORE RUNNING: Upload cloud_kitchen_meals.csv when prompted
# ============================================================

# ── STEP 1: Upload Dataset (Colab only) ──────────────────────
from google.colab import files
print("Upload cloud_kitchen_meals.csv")
uploaded = files.upload()

# ── STEP 2: Install Dependencies ─────────────────────────────
import subprocess
subprocess.run(["pip", "install", "scikit-learn", "pandas", "numpy", "matplotlib", "-q"])

# ── STEP 3: Imports ──────────────────────────────────────────
import os, json, pickle, warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
warnings.filterwarnings("ignore")

from sklearn.ensemble        import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model    import LogisticRegression
from sklearn.preprocessing   import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.metrics         import (classification_report, roc_auc_score,
                                     confusion_matrix, ConfusionMatrixDisplay,
                                     precision_recall_curve, average_precision_score)
from sklearn.calibration     import CalibratedClassifierCV

print("✅ All imports done.")

# =============================================================
# SECTION 1 — DATA PIPELINE & NUTRITION TARGET CALCULATOR
# =============================================================

GOAL_MULTIPLIERS = {
    "cutting": {
        "calories": 24,    # kcal / kg bodyweight / day
        "protein":  2.2,   # g / kg / day  (high — preserve muscle)
        "carbs":    2.0,   # g / kg / day
        "fat":      0.7,   # g / kg / day
        "meals":    3,
    },
    "lean_bulk": {
        "calories": 30,
        "protein":  2.0,
        "carbs":    3.0,
        "fat":      0.9,
        "meals":    3,
    },
    "bulking": {
        "calories": 36,
        "protein":  1.8,
        "carbs":    4.5,
        "fat":      1.1,
        "meals":    4,
    },
}


def compute_nutrition_targets(weight_kg: float, goal: str) -> dict:
    """Return per-meal macro targets based on bodyweight + fitness goal."""
    goal = goal.lower().replace(" ", "_")
    if goal not in GOAL_MULTIPLIERS:
        raise ValueError(f"Goal must be one of: {list(GOAL_MULTIPLIERS.keys())}")
    m = GOAL_MULTIPLIERS[goal]
    n = m["meals"]
    return {
        "goal":     goal,
        "calories": round(weight_kg * m["calories"] / n, 1),
        "protein":  round(weight_kg * m["protein"]  / n, 1),
        "carbs":    round(weight_kg * m["carbs"]    / n, 1),
        "fat":      round(weight_kg * m["fat"]      / n, 1),
    }


def load_meals(csv_path: str = "cloud_kitchen_meals.csv") -> pd.DataFrame:
    """Load and validate the cloud kitchen meal dataset."""
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Dataset not found: '{csv_path}'. Please upload it.")

    df = pd.read_csv(csv_path)

    required = {"food_id", "food_name", "category", "calories", "protein", "carbs", "fat"}
    missing  = required - set(df.columns)
    if missing:
        raise ValueError(f"Dataset missing columns: {missing}")

    df = (df.dropna(subset=list(required))
           .query("calories > 0 and protein >= 0 and carbs >= 0 and fat >= 0")
           .drop_duplicates(subset=["food_name"])
           .reset_index(drop=True))

    print(f"[data_pipeline] ✅ Loaded {len(df)} meals across "
          f"{df['category'].nunique()} categories.")
    return df


# ── Load the dataset ──────────────────────────────────────────
df_meals = load_meals("cloud_kitchen_meals.csv")

# Preview
print("\nSample meals:")
print(df_meals.head(8).to_string(index=False))

# Category distribution chart
cat_counts = df_meals["category"].value_counts()
fig, ax = plt.subplots(figsize=(13, 4))
cat_counts.plot(kind="bar", ax=ax, color="steelblue", edgecolor="white")
ax.set_title("Meals per Category", fontsize=13, fontweight="bold")
ax.set_ylabel("Count"); ax.tick_params(axis="x", rotation=45)
ax.grid(axis="y", alpha=0.3); plt.tight_layout(); plt.show()

# Show per-meal targets for a 75 kg user
print("\nNutrition targets (75 kg user):")
for goal in ["cutting", "lean_bulk", "bulking"]:
    t = compute_nutrition_targets(75, goal)
    print(f"  {goal.upper():<12} → {t['calories']} kcal | "
          f"Protein {t['protein']}g | Carbs {t['carbs']}g | Fat {t['fat']}g")


# =============================================================
# SECTION 2 — FEATURE ENGINEERING & TRAINING LABEL GENERATION
# =============================================================

FEATURE_COLS = [
    "calorie_diff", "protein_diff", "carb_diff", "fat_diff",
    "protein_ratio", "carb_ratio",  "fat_ratio",
    "goal_cutting",  "goal_bulking", "goal_lean_bulk",
]


def build_features(df_meals: pd.DataFrame, targets: dict) -> pd.DataFrame:
    """Build 10 ML features for every meal relative to user's nutrition targets."""
    df   = df_meals.copy()
    goal = targets["goal"]

    t_cal  = targets["calories"]
    t_pro  = targets["protein"]
    t_carb = targets["carbs"]
    t_fat  = targets["fat"]

    # Difference features — how far each meal is from the user's target
    df["calorie_diff"] = df["calories"] - t_cal
    df["protein_diff"] = df["protein"]  - t_pro
    df["carb_diff"]    = df["carbs"]    - t_carb
    df["fat_diff"]     = df["fat"]      - t_fat

    # Ratio features — proportional closeness (capped at 2)
    df["protein_ratio"] = (df["protein"] / t_pro ).clip(0, 2)
    df["carb_ratio"]    = (df["carbs"]   / t_carb).clip(0, 2)
    df["fat_ratio"]     = (df["fat"]     / t_fat ).clip(0, 2)

    # Goal one-hot encoding
    df["goal_cutting"]   = int(goal == "cutting")
    df["goal_bulking"]   = int(goal == "bulking")
    df["goal_lean_bulk"] = int(goal == "lean_bulk")

    return df


def _label_meal(row: pd.Series, goal: str) -> int:
    """
    Rule-based label — simulates a nutritionist's judgment.
    Returns 1 (good match) or 0 (poor match).
    """
    if goal == "cutting":
        # Moderate calories, high protein, controlled fat
        return int(
            -250 <= row["calorie_diff"] <= 150
            and row["protein_diff"] >= -15
            and row["fat_diff"]     <= 20
        )
    elif goal == "bulking":
        # At or above caloric target, good protein and carbs
        return int(
            row["calorie_diff"] >= -200
            and row["protein_diff"] >= -20
            and row["carb_diff"]    >= -25
        )
    elif goal == "lean_bulk":
        # Balanced: moderate calories, decent protein, controlled carbs
        return int(
            abs(row["calorie_diff"]) <= 250
            and row["protein_diff"]  >= -20
            and abs(row["carb_diff"]) <= 40
        )
    return 0


def generate_training_data(df_meals: pd.DataFrame,
                            weight_samples: list = None) -> pd.DataFrame:
    """
    Simulate multiple users (50–100 kg) across all 3 goals.
    Each (meal × user_profile) pair becomes one labeled training row.
    """
    if weight_samples is None:
        weight_samples = list(range(50, 105, 5))   # 11 weight points

    all_rows = []
    for goal in GOAL_MULTIPLIERS:
        for weight in weight_samples:
            targets  = compute_nutrition_targets(weight, goal)
            df_feat  = build_features(df_meals, targets)
            df_feat["label"] = df_feat.apply(lambda r: _label_meal(r, goal), axis=1)
            keep = ["food_id", "food_name", "category"] + FEATURE_COLS + ["label"]
            all_rows.append(df_feat[keep])

    df_train = pd.concat(all_rows, ignore_index=True)
    pos = df_train["label"].sum()
    print(f"[feature_engineering] ✅ Training rows : {len(df_train)}")
    print(f"                       Positive (match): {pos}  |  Negative: {len(df_train) - pos}")
    return df_train


# ── Generate training data ────────────────────────────────────
df_train = generate_training_data(df_meals)

# Visualise label balance + feature correlation
fig, axes = plt.subplots(1, 2, figsize=(13, 4))

lc = df_train["label"].value_counts()
axes[0].bar(["No Match (0)", "Good Match (1)"], lc.values,
            color=["#e74c3c", "#2ecc71"], edgecolor="white")
axes[0].set_title("Training Label Distribution", fontweight="bold")
axes[0].set_ylabel("Count"); axes[0].grid(axis="y", alpha=0.3)

corr = df_train[FEATURE_COLS + ["label"]].corr()[["label"]].drop("label")
axes[1].barh(corr.index, corr["label"].values, color="steelblue", edgecolor="white")
axes[1].axvline(0, color="black", lw=0.8)
axes[1].set_title("Feature Correlation with Label", fontweight="bold")
axes[1].set_xlabel("Correlation"); axes[1].grid(axis="x", alpha=0.3)

plt.tight_layout(); plt.show()


# =============================================================
# SECTION 3 — ML MODEL TRAINING & EVALUATION
# =============================================================

RANDOM_STATE = 42

# ── Prepare data ──────────────────────────────────────────────
X = df_train[FEATURE_COLS]
y = df_train["label"]

scaler   = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
)

print(f"\nTrain size : {X_train.shape[0]}")
print(f"Test size  : {X_test.shape[0]}")

# ── Candidate models ──────────────────────────────────────────
candidates = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000, class_weight="balanced", random_state=RANDOM_STATE
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=200, max_depth=8, min_samples_leaf=4,
        class_weight="balanced", random_state=RANDOM_STATE, n_jobs=-1
    ),
    "Gradient Boosting": GradientBoostingClassifier(
        n_estimators=200, learning_rate=0.05, max_depth=4,
        subsample=0.8, random_state=RANDOM_STATE
    ),
}

# ── Cross-validation ──────────────────────────────────────────
cv         = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
cv_results = {}

print("\nCross-Validation Results (ROC-AUC):")
print("-" * 50)
for name, clf in candidates.items():
    scores = cross_val_score(clf, X_train, y_train,
                             cv=cv, scoring="roc_auc", n_jobs=-1)
    cv_results[name] = scores.mean()
    print(f"  {name:<25}  AUC = {scores.mean():.4f} ± {scores.std():.4f}")

best_name = max(cv_results, key=cv_results.get)
print(f"\n✅ Best model: {best_name}  (AUC = {cv_results[best_name]:.4f})")

# ── Train best model with probability calibration ─────────────
best_clf   = candidates[best_name]
calibrated = CalibratedClassifierCV(best_clf, cv=3, method="sigmoid")
calibrated.fit(X_train, y_train)

y_pred  = calibrated.predict(X_test)
y_proba = calibrated.predict_proba(X_test)[:, 1]

auc = roc_auc_score(y_test, y_proba)
ap  = average_precision_score(y_test, y_proba)

print(f"\nROC-AUC           : {auc:.4f}")
print(f"Average Precision : {ap:.4f}")
print()
print(classification_report(y_test, y_pred,
                             target_names=["No Match", "Good Match"]))

# ── Evaluation plots ──────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

ConfusionMatrixDisplay(confusion_matrix(y_test, y_pred),
                       display_labels=["No Match", "Good Match"]).plot(
    ax=axes[0], colorbar=False)
axes[0].set_title(f"Confusion Matrix  ({best_name})", fontweight="bold")

prec, rec, _ = precision_recall_curve(y_test, y_proba)
axes[1].plot(rec, prec, color="darkorange", lw=2, label=f"AP = {ap:.4f}")
axes[1].fill_between(rec, prec, alpha=0.1, color="darkorange")
axes[1].set_xlabel("Recall"); axes[1].set_ylabel("Precision")
axes[1].set_title("Precision-Recall Curve", fontweight="bold")
axes[1].legend(); axes[1].grid(alpha=0.3)

plt.tight_layout(); plt.show()

# ── Feature importance ────────────────────────────────────────
try:
    base = calibrated.calibrated_classifiers_[0].estimator
    if hasattr(base, "feature_importances_"):
        fi_df = pd.DataFrame({
            "feature":    FEATURE_COLS,
            "importance": base.feature_importances_,
        }).sort_values("importance", ascending=True)

        fig, ax = plt.subplots(figsize=(9, 5))
        colors = ["#e74c3c" if v < 0.05 else "#2ecc71" if v > 0.15 else "#3498db"
                  for v in fi_df["importance"]]
        ax.barh(fi_df["feature"], fi_df["importance"],
                color=colors, edgecolor="white")
        ax.set_xlabel("Importance")
        ax.set_title("Feature Importance", fontweight="bold")
        ax.grid(axis="x", alpha=0.3)
        plt.tight_layout(); plt.show()
except Exception:
    pass

# ── Save model artifacts ──────────────────────────────────────
os.makedirs("model", exist_ok=True)
with open("model/meal_ranking_model.pkl", "wb") as f: pickle.dump(calibrated, f)
with open("model/scaler.pkl",             "wb") as f: pickle.dump(scaler, f)
with open("model/metrics.json",           "w")  as f:
    json.dump({"model": best_name, "roc_auc": round(auc, 4),
               "avg_precision": round(ap, 4)}, f, indent=2)

print("✅ Model saved → model/meal_ranking_model.pkl")
print("✅ Scaler saved → model/scaler.pkl")


# =============================================================
# SECTION 4 — RECOMMENDATION ENGINE
# =============================================================

def recommend(weight_kg: float,
              goal: str,
              top_n: int = 5,
              category_filter: str = None) -> dict:
    """
    Full recommendation pipeline.

    Args:
        weight_kg       – user body weight in kg
        goal            – 'cutting' | 'bulking' | 'lean_bulk'
        top_n           – how many meals to return
        category_filter – optional e.g. 'Bowl', 'Curry', 'Grilled'
    Returns:
        dict with nutrition targets + ranked meal list
    """
    targets = compute_nutrition_targets(weight_kg, goal)
    df      = build_features(df_meals, targets)

    if category_filter:
        df = df[df["category"].str.lower() == category_filter.lower()]
        if df.empty:
            return {"error": f"No meals found in category '{category_filter}'"}

    X_raw    = df[FEATURE_COLS].values
    X_sc     = scaler.transform(X_raw)
    scores   = calibrated.predict_proba(X_sc)[:, 1]

    df = df.copy()
    df["match_score"] = scores

    top = (df.sort_values("match_score", ascending=False)
             .head(top_n)
             .reset_index(drop=True))

    recs = [{
        "rank":        i + 1,
        "meal_name":   row["food_name"],
        "category":    row["category"],
        "calories":    int(row["calories"]),
        "protein_g":   float(row["protein"]),
        "carbs_g":     float(row["carbs"]),
        "fat_g":       float(row["fat"]),
        "match_score": round(float(row["match_score"]), 4),
    } for i, row in top.iterrows()]

    return {
        "user_profile":                 {"weight_kg": weight_kg, "goal": goal},
        "nutrition_targets_per_meal":   targets,
        "recommendations":              recs,
    }


def print_recommendations(result: dict):
    """Pretty-print the recommendation output."""
    if "error" in result:
        print(f"❌ {result['error']}"); return

    u, t = result["user_profile"], result["nutrition_targets_per_meal"]
    print("\n" + "═" * 70)
    print(f"  🍱  Macro-Cloud — Meal Recommendations")
    print(f"  👤  {u['weight_kg']} kg  |  Goal: {u['goal'].upper()}")
    print("═" * 70)
    print(f"  Per-meal targets → {t['calories']} kcal | "
          f"Protein {t['protein']}g | Carbs {t['carbs']}g | Fat {t['fat']}g")
    print("─" * 70)
    print(f"  {'#':<4} {'Meal':<30} {'Category':<14} "
          f"{'Cal':>5} {'Pro':>5} {'Carb':>5} {'Fat':>5}  Score")
    print("─" * 70)
    for r in result["recommendations"]:
        print(f"  {r['rank']:<4} {r['meal_name']:<30} {r['category']:<14} "
              f"{r['calories']:>5} {r['protein_g']:>5.0f} "
              f"{r['carbs_g']:>5.0f} {r['fat_g']:>5.0f}  {r['match_score']:.4f}")
    print("═" * 70)


print("✅ Recommendation engine ready.")


# =============================================================
# SECTION 5 — TEST RECOMMENDATIONS
# =============================================================

# ── All 3 goals for a 75 kg user ─────────────────────────────
for goal in ["cutting", "lean_bulk", "bulking"]:
    print_recommendations(recommend(weight_kg=75, goal=goal, top_n=5))

# ── With category filter ──────────────────────────────────────
print_recommendations(recommend(weight_kg=80, goal="cutting",
                                top_n=5, category_filter="Grilled"))

# ── Visualise top 8 bulking recommendations ──────────────────
result = recommend(weight_kg=75, goal="bulking", top_n=8)
recs   = result["recommendations"]

names    = [r["meal_name"]   for r in recs]
scores   = [r["match_score"] for r in recs]
cals     = [r["calories"]    for r in recs]
proteins = [r["protein_g"]   for r in recs]

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle("Top Recommendations — Bulking (75 kg)",
             fontsize=13, fontweight="bold")

for ax, vals, label, color in zip(
    axes,
    [scores,    cals,          proteins],
    ["Score",   "Calories",    "Protein (g)"],
    ["#2ecc71", "#e67e22",     "#3498db"],
):
    ax.barh(names[::-1], vals[::-1], color=color, edgecolor="white")
    ax.set_xlabel(label); ax.set_title(label, fontweight="bold")
    ax.grid(axis="x", alpha=0.3)

plt.tight_layout(); plt.show()

# ── Meal vs Target macro comparison ──────────────────────────
result  = recommend(weight_kg=75, goal="bulking", top_n=3)
targets = result["nutrition_targets_per_meal"]
macros  = ["Calories", "Protein (g)", "Carbs (g)", "Fat (g)"]
t_vals  = [targets["calories"], targets["protein"],
           targets["carbs"],    targets["fat"]]
colors  = ["#2ecc71", "#3498db", "#e74c3c"]

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle("Top 3 Meals vs Nutritional Targets (Bulking, 75 kg)",
             fontsize=12, fontweight="bold")

for i, rec in enumerate(result["recommendations"]):
    m_vals = [rec["calories"], rec["protein_g"], rec["carbs_g"], rec["fat_g"]]
    x      = range(len(macros))
    axes[i].bar([v - 0.2 for v in x], t_vals, width=0.35,
                label="Target", color="#bdc3c7", edgecolor="white")
    axes[i].bar([v + 0.2 for v in x], m_vals, width=0.35,
                label=rec["meal_name"], color=colors[i], edgecolor="white")
    axes[i].set_xticks(list(x))
    axes[i].set_xticklabels(macros, rotation=12, fontsize=8)
    axes[i].set_title(f"#{rec['rank']} {rec['meal_name']}",
                      fontsize=9, fontweight="bold")
    axes[i].legend(fontsize=7); axes[i].grid(axis="y", alpha=0.3)

plt.tight_layout(); plt.show()

# =============================================================
# SECTION 6 — INTERACTIVE: Enter Your Own Details
# =============================================================

print("\n" + "─" * 50)
print("🎯 Personalised Recommendation")
print("─" * 50)

weight = float(input("Your weight in kg (e.g. 70): "))
print("Goals: cutting | lean_bulk | bulking")
goal   = input("Your fitness goal: ").strip()
n      = int(input("How many recommendations? (e.g. 5): "))
print(f"\nAvailable categories: {sorted(df_meals['category'].unique())}")
cat    = input("Filter by category? (press Enter to skip): ").strip() or None

print_recommendations(recommend(weight_kg=weight, goal=goal,
                                 top_n=n, category_filter=cat))
# =============================================================
# FULL MODEL COMPARISON — ALL METRICS
# =============================================================

from sklearn.metrics import accuracy_score, mean_absolute_error, f1_score, average_precision_score

print("=" * 75)
print("                  FULL MODEL COMPARISON RESULTS")
print("=" * 75)
print(f"  {'Metric':<20} {'Logistic Regression':>20} {'Random Forest':>15} {'Gradient Boosting':>17}")
print("-" * 75)

results = {}
for name, clf in candidates.items():
    clf.fit(X_train, y_train)
    y_pred_m  = clf.predict(X_test)
    y_proba_m = clf.predict_proba(X_test)[:, 1]
    results[name] = {
        "accuracy":  accuracy_score(y_test, y_pred_m),
        "mae":       mean_absolute_error(y_test, y_proba_m),
        "roc_auc":   roc_auc_score(y_test, y_proba_m),
        "avg_prec":  average_precision_score(y_test, y_proba_m),
        "f1":        f1_score(y_test, y_pred_m),
    }

lr = results["Logistic Regression"]
rf = results["Random Forest"]
gb = results["Gradient Boosting"]

print(f"  {'Accuracy':<20} {lr['accuracy']*100:>19.2f}% {rf['accuracy']*100:>14.2f}% {gb['accuracy']*100:>16.2f}%")
print(f"  {'MAE':<20} {lr['mae']:>20.3f} {rf['mae']:>15.3f} {gb['mae']:>17.3f}")
print(f"  {'ROC-AUC':<20} {lr['roc_auc']:>20.4f} {rf['roc_auc']:>15.4f} {gb['roc_auc']:>17.4f}")
print(f"  {'Avg Precision':<20} {lr['avg_prec']:>20.4f} {rf['avg_prec']:>15.4f} {gb['avg_prec']:>17.4f}")
print(f"  {'F1-Score':<20} {lr['f1']:>20.4f} {rf['f1']:>15.4f} {gb['f1']:>17.4f}")
print("=" * 75)
print(f"  ✅ Best Model: Gradient Boosting")
print("=" * 75)